server.port=8087
spring.application.name=whatsapp-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

twilio.account.sid=REMOVED
twilio.auth.token=REMOVED
twilio.whatsapp.number=+14155238886